name: Build native image

on:
  workflow_dispatch:
  push:
    branches: [ "native" ]

env:
  IMAGE_NAME: note-keeper-native

jobs:
  build-and-upload:
    runs-on: darvik-minipc
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build native docker image
        run: docker build -f Dockerfile.native -t "$IMAGE_NAME:latest" .

      - name: Save image archive
        run: docker save "$IMAGE_NAME:latest" | gzip > note-keeper-native.tar.gz

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: note-keeper-native
          path: note-keeper-native.tar.gz
          retention-days: 14
