name: Synology

on:
  push:
    branches: [ "master" ]

env:
  TARGET_PORT: 9081
  CONTAINER_NAME: note-keeper

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          export DOCKER_API_VERSION=1.43
          docker build -t localhost/$CONTAINER_NAME:latest .

      # Перезапускаем контейнер
      - name: Restart ai-agent
        run: |
          export DOCKER_API_VERSION=1.43
          docker rm -f $CONTAINER_NAME
          docker run --env-file /volume1/docker/$CONTAINER_NAME/.env \
            -d -p $TARGET_PORT:8080 \
            --volume /volume1/docker/$CONTAINER_NAME/etc:/app/etc:ro \
            --volume /volume1/docker/$CONTAINER_NAME/var:/app/var:rw \
            --volume /volume1/docker/$CONTAINER_NAME/.env:/app/.env:ro \
            --name $CONTAINER_NAME localhost/$CONTAINER_NAME:latest \
