apiVersion: v1
kind: Service
metadata:
  name: note-keeper
  namespace: note-keeper
  labels:
    app: note-keeper
spec:
  type: NodePort
  selector:
    app: note-keeper
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30081
